query ($owner: String!, $repo: String!, $number: Int!, $after: String) {
    repository(owner: $owner, name: $repo) {
        issue(number: $number) {
            timelineItems(
                first: 100
                after: $after
                itemTypes: [CROSS_REFERENCED_EVENT, CONNECTED_EVENT]
            ) {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                nodes {
                    __typename
                    ... on CrossReferencedEvent {
                        source {
                            __typename
                            ... on PullRequest {
                                number
                            }
                        }
                    }
                    ... on ConnectedEvent {
                        subject {
                            __typename
                            ... on PullRequest {
                                number
                            }
                        }
                    }
                }
            }
        }
    }
}
