query ($owner: String!, $repo: String!, $number: Int!) {
    repository(owner: $owner, name: $repo) {
        issue(number: $number) {
            timelineItems(
                first: 100
                itemTypes: [CROSS_REFERENCED_EVENT, CONNECTED_EVENT]
            ) {
                nodes {
                    __typename
                    ... on CrossReferencedEvent {
                        source {
                            __typename
                            ... on PullRequest {
                                number
                            }
                        }
                    }
                    ... on ConnectedEvent {
                        subject {
                            __typename
                            ... on PullRequest {
                                number
                            }
                        }
                    }
                }
            }
        }
    }
}
